SET IDENTITY_INSERT [dbo].[Category] ON
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'OPP袋 テープ付', N'https://store.shopping.yahoo.co.jp/workupstore/oppc2dea5c4.html', 1)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'OPP袋 テープなし', N'https://store.shopping.yahoo.co.jp/workupstore/oppc2dea5c3.html', 2)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'破れにくい CPP袋', N'https://store.shopping.yahoo.co.jp/workupstore/c7cba4eca4.html', 3)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'片面白 PP袋', N'https://store.shopping.yahoo.co.jp/workupstore/cad2ccccc7.html', 4)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'OPP袋 本体側テープ付', N'https://store.shopping.yahoo.co.jp/workupstore/oppc2decbd.html', 5)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'ヘッダー付 OPP袋', N'https://store.shopping.yahoo.co.jp/workupstore/a5d8a5c3a5.html', 6)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'ブックカバー・書籍関連', N'https://store.shopping.yahoo.co.jp/workupstore/a5d6a5c3a5.html', 7)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'CD・DVD・BD・ゲーム・レコード', N'https://store.shopping.yahoo.co.jp/workupstore/cda1a6dvda2.html', 8)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'トレカ・各種カード用', N'https://store.shopping.yahoo.co.jp/workupstore/a5c8a5eca5.html', 9)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'ハガキ・ポストカード用', N'https://store.shopping.yahoo.co.jp/workupstore/a5cfa5aca5.html', 10)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'写真用', N'https://store.shopping.yahoo.co.jp/workupstore/bcccbfbfcd.html', 11)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'名刺用', N'https://store.shopping.yahoo.co.jp/workupstore/b9bccbc2dec.html', 12)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'フレームシール袋(アパレル用)', N'https://store.shopping.yahoo.co.jp/workupstore/a5d5a5eca1.html', 13)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'手提げ透明袋', N'https://store.shopping.yahoo.co.jp/workupstore/bceac4f3a4.html', 14)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'ガゼットOPP袋', N'https://store.shopping.yahoo.co.jp/workupstore/a5aca5bca5.html', 15)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'ペットボトル袋', N'https://store.shopping.yahoo.co.jp/workupstore/a5daa5c3a5.html', 16)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'デリバリーパック', N'https://store.shopping.yahoo.co.jp/workupstore/52a7ac5aae5.html', 17)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'納品書袋(片開き袋)', N'https://store.shopping.yahoo.co.jp/workupstore/c7bcc9cabd.html', 18)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'すべりにくい PP袋', N'https://store.shopping.yahoo.co.jp/workupstore/a4b9a4d9a4.html', 19)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N' 販促マスク用袋', N'https://store.shopping.yahoo.co.jp/workupstore/c8cec2a5a5.html', 20)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'カットテープ付きOPP袋', N'https://store.shopping.yahoo.co.jp/workupstore/a5aba5c3a5.html', 21)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'OPPシート', N'https://store.shopping.yahoo.co.jp/workupstore/oppa5b7a1b.html', 22)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'OPPロール', N'https://store.shopping.yahoo.co.jp/workupstore/oppa5eda1b.html', 23)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'お弁当シート', N'https://store.shopping.yahoo.co.jp/workupstore/a4aacadbc5.html', 24)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'OPP花束用袋(三角袋)', N'https://store.shopping.yahoo.co.jp/workupstore/oppb2d6c2a.html', 25)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'スタンドパック', N'https://store.shopping.yahoo.co.jp/workupstore/a5b9a5bfa5.html', 26)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'野菜用ボードンOPP袋', N'https://store.shopping.yahoo.co.jp/workupstore/cceebadacd.html', 27)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'ポケットファイル用リフィル', N'https://store.shopping.yahoo.co.jp/workupstore/a5dda5b1a5.html', 28)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'寒さに強いLLDPE袋', N'https://store.shopping.yahoo.co.jp/workupstore/b4a8a4b5a4.html', 29)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'セキュリティーテープ', N'https://store.shopping.yahoo.co.jp/workupstore/52bb55aadaa.html', 30)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'チャック付きポリ袋', N'https://store.shopping.yahoo.co.jp/workupstore/aa5a52ec135.html', 31)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'貴重品袋', N'https://store.shopping.yahoo.co.jp/workupstore/b5aebdc5c9.html', 32)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'カレンダー用ポリチューブ', N'https://store.shopping.yahoo.co.jp/workupstore/a5aba5eca5.html', 33)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'ポリ袋', N'https://store.shopping.yahoo.co.jp/workupstore/a5dda5eac2.html', 34)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'シール＆台紙', N'https://store.shopping.yahoo.co.jp/workupstore/cb1a55b27aa.html', 35)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'宅配ビニール袋', N'https://store.shopping.yahoo.co.jp/workupstore/c2f0c7dba5.html', 36)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'格安!アウトレット', N'https://store.shopping.yahoo.co.jp/workupstore/b3cab0c221.html', 37)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'お札用OPP袋', N'https://store.shopping.yahoo.co.jp/workupstore/a4aabba5cd.html', 38)
INSERT INTO [dbo].[Category] ([Name], [Url], [CategoryId]) VALUES (N'うちわ用OPP袋', N'https://store.shopping.yahoo.co.jp/workupstore/a4a6a4c1a4.html', 39)
SET IDENTITY_INSERT [dbo].[Category] OFF
