SET IDENTITY_INSERT [dbo].[Category] ON
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (1, N'OPP袋 テープ付', N'https://store.shopping.yahoo.co.jp/workupstore/oppc2dea5c4.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (2, N'OPP袋 テープなし', N'https://store.shopping.yahoo.co.jp/workupstore/oppc2dea5c3.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (3, N'破れにくい CPP袋', N'https://store.shopping.yahoo.co.jp/workupstore/c7cba4eca4.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (4, N'片面白 PP袋', N'https://store.shopping.yahoo.co.jp/workupstore/cad2ccccc7.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (5, N'OPP袋 本体側テープ付', N'https://store.shopping.yahoo.co.jp/workupstore/oppc2decbd.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (6, N'ヘッダー付 OPP袋', N'https://store.shopping.yahoo.co.jp/workupstore/a5d8a5c3a5.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (7, N'ブックカバー・書籍関連', N'https://store.shopping.yahoo.co.jp/workupstore/a5d6a5c3a5.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (8, N'CD・DVD・BD・ゲーム・レコード', N'https://store.shopping.yahoo.co.jp/workupstore/cda1a6dvda2.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (9, N'トレカ・各種カード用', N'https://store.shopping.yahoo.co.jp/workupstore/a5c8a5eca5.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (10, N'ハガキ・ポストカード用', N'https://store.shopping.yahoo.co.jp/workupstore/a5cfa5aca5.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (11, N'写真用', N'https://store.shopping.yahoo.co.jp/workupstore/bcccbfbfcd.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (12, N'名刺用', N'https://store.shopping.yahoo.co.jp/workupstore/b9bccbc2dec.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (13, N'フレームシール袋(アパレル用)', N'https://store.shopping.yahoo.co.jp/workupstore/a5d5a5eca1.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (14, N'手提げ透明袋', N'https://store.shopping.yahoo.co.jp/workupstore/bceac4f3a4.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (15, N'ガゼットOPP袋', N'https://store.shopping.yahoo.co.jp/workupstore/a5aca5bca5.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (16, N'ペットボトル袋', N'https://store.shopping.yahoo.co.jp/workupstore/a5daa5c3a5.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (17, N'デリバリーパック', N'https://store.shopping.yahoo.co.jp/workupstore/52a7ac5aae5.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (18, N'納品書袋(片開き袋)', N'https://store.shopping.yahoo.co.jp/workupstore/c7bcc9cabd.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (19, N'すべりにくい PP袋', N'https://store.shopping.yahoo.co.jp/workupstore/a4b9a4d9a4.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (20, N' 販促マスク用袋', N'https://store.shopping.yahoo.co.jp/workupstore/c8cec2a5a5.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (21, N'カットテープ付きOPP袋', N'https://store.shopping.yahoo.co.jp/workupstore/a5aba5c3a5.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (22, N'OPPシート', N'https://store.shopping.yahoo.co.jp/workupstore/oppa5b7a1b.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (23, N'OPPロール', N'https://store.shopping.yahoo.co.jp/workupstore/oppa5eda1b.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (24, N'お弁当シート', N'https://store.shopping.yahoo.co.jp/workupstore/a4aacadbc5.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (25, N'OPP花束用袋(三角袋)', N'https://store.shopping.yahoo.co.jp/workupstore/oppb2d6c2a.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (26, N'スタンドパック', N'https://store.shopping.yahoo.co.jp/workupstore/a5b9a5bfa5.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (27, N'野菜用ボードンOPP袋', N'https://store.shopping.yahoo.co.jp/workupstore/cceebadacd.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (28, N'ポケットファイル用リフィル', N'https://store.shopping.yahoo.co.jp/workupstore/a5dda5b1a5.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (29, N'寒さに強いLLDPE袋', N'https://store.shopping.yahoo.co.jp/workupstore/b4a8a4b5a4.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (30, N'セキュリティーテープ', N'https://store.shopping.yahoo.co.jp/workupstore/52bb55aadaa.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (31, N'チャック付きポリ袋', N'https://store.shopping.yahoo.co.jp/workupstore/aa5a52ec135.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (32, N'貴重品袋', N'https://store.shopping.yahoo.co.jp/workupstore/b5aebdc5c9.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (33, N'カレンダー用ポリチューブ', N'https://store.shopping.yahoo.co.jp/workupstore/a5aba5eca5.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (34, N'ポリ袋', N'https://store.shopping.yahoo.co.jp/workupstore/a5dda5eac2.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (35, N'シール＆台紙', N'https://store.shopping.yahoo.co.jp/workupstore/cb1a55b27aa.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (36, N'宅配ビニール袋', N'https://store.shopping.yahoo.co.jp/workupstore/c2f0c7dba5.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (37, N'格安!アウトレット', N'https://store.shopping.yahoo.co.jp/workupstore/b3cab0c221.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (38, N'お札用OPP袋', N'https://store.shopping.yahoo.co.jp/workupstore/a4aabba5cd.html')
INSERT INTO [dbo].[Category] ([CategoryId], [Name], [Url]) VALUES (39, N'うちわ用OPP袋', N'https://store.shopping.yahoo.co.jp/workupstore/a4a6a4c1a4.html')
SET IDENTITY_INSERT [dbo].[Category] OFF
